import { LegalPage } from '@/components/legal-page';

export default function Privacy() { return <LegalPage title="Privacy Policy">
  <p>Veyrasoft, based in Darwin, Northern Territory, Australia, operates Veyra. This policy explains how we collect, use, disclose and protect personal information through the Veyra website, browser extension and support services.</p>
  <h2>Information we collect</h2><p>We may collect your name, email address, account identifiers, licence and purchase status, messages you send to support, and limited technical information such as browser version, device type, error reports, IP address and service activity. Our payment provider processes payment-card details; Veyrasoft receives transaction details but does not store complete card numbers.</p>
  <h2>Workspace and browser information</h2><p>Veyra may handle bookmarks, boards, notes, wallpapers and settings to provide the features you choose. Local-only information remains in browser storage unless you enable sync, export it, or send it to us for support. We do not sell bookmark contents or use them for targeted advertising.</p>
  <h2>How we use information</h2><ul><li>Provide accounts, synchronisation, licensing and customer support.</li><li>Process purchases, refunds and fraud checks.</li><li>Maintain security, diagnose errors and improve performance.</li><li>Send service messages and, only where permitted, product updates.</li><li>Meet legal, tax and regulatory obligations.</li></ul>
  <h2>Browser permissions</h2><p>The extension requests permissions needed to replace the new-tab page, save the active tab, import bookmarks, store preferences and support optional sign-in or sync. Veyra uses permissions only for the feature described in the extension interface and store listing.</p>
  <h2>Disclosure and overseas processing</h2><p>We may share limited information with service providers for hosting, authentication, payments, email, security and diagnostics, and with authorities where legally required. Providers may process information in Australia, the United States or other countries in which they operate. We take reasonable steps to use reputable providers and appropriate contractual or technical safeguards.</p>
  <h2>Retention and security</h2><p>We retain information only for as long as needed to provide Veyra, keep required business and tax records, resolve disputes and protect against fraud. We use reasonable access controls, encryption in transit and data-minimisation practices. No internet service can guarantee absolute security.</p>
  <h2>Access, correction and deletion</h2><p>You can remove locally stored data through the extension and may request access to, correction of, or deletion of account information by emailing <a href="mailto:veyrasoft@gmail.com">veyrasoft@gmail.com</a>. Some information may be retained where legally required or necessary to protect legitimate interests.</p>
  <h2>Complaints</h2><p>Email us with enough detail to investigate a privacy concern. We will acknowledge and respond within a reasonable period. If you are not satisfied and the Privacy Act 1988 applies, you may contact the Office of the Australian Information Commissioner.</p>
  <h2>Children and changes</h2><p>Veyra is not directed to children under 13, and we do not knowingly collect their personal information. We may update this policy when our practices change; the effective date above identifies the current version.</p>
</LegalPage>; }
