import { LegalPage } from '@/components/legal-page';

export default function Terms() { return <LegalPage title="Terms of Service">
  <p>These Terms form an agreement between you and Veyrasoft of Darwin, Northern Territory, Australia for use of the Veyra website, browser extension and related services. By purchasing, installing or using Veyra, you accept these Terms and the Licence Agreement.</p>
  <h2>Eligibility and accounts</h2><p>You must be at least 18, or have permission from a parent or legal guardian, and be legally able to enter this agreement. You are responsible for accurate account information, keeping credentials secure and activity performed through your account.</p>
  <h2>Plans and payment</h2><p>The one-year pass provides access for 12 months from activation and does not automatically renew. Lifetime access continues for the commercial life of Veyra, subject to supported browsers, these Terms and any lawful termination. Prices, currency, taxes and payment-provider terms are displayed at checkout.</p>
  <h2>Acceptable use</h2><p>You must not use Veyra unlawfully; interfere with the service or other users; bypass licence, access or security controls; distribute malware; scrape or overload our systems; resell access; or reverse engineer protected software except where applicable law expressly permits.</p>
  <h2>Your content</h2><p>You retain ownership of bookmarks, notes and other content you add. You give Veyrasoft only the limited rights required to host, process, sync, back up and display that content for you. You are responsible for ensuring you have the right to save or share it.</p>
  <h2>Third-party services</h2><p>Veyra may interact with browsers, identity providers, websites and payment services that we do not control. Their terms and availability apply separately. We are not responsible for third-party content or changes, but this does not limit rights that cannot be excluded by law.</p>
  <h2>Updates and availability</h2><p>We may release fixes, add or remove features, change integrations, or discontinue Veyra. We will take reasonable steps to avoid unnecessary disruption. Lifetime access does not guarantee that every present feature or third-party integration will remain available forever.</p>
  <h2>Consumer guarantees</h2><p>Nothing in these Terms excludes, restricts or modifies any guarantee, right or remedy that cannot lawfully be excluded, including rights under the Australian Consumer Law. Where permitted, our liability is limited to supplying the service again or paying the reasonable cost of having it supplied again.</p>
  <h2>Liability</h2><p>To the maximum extent permitted by law, Veyrasoft is not liable for indirect, special or consequential loss, lost profits, or lost data that could reasonably have been backed up. Our total liability for claims connected with Veyra is limited to the amount you paid during the 12 months before the event giving rise to the claim, except where such a limit is prohibited.</p>
  <h2>Suspension and termination</h2><p>We may suspend or terminate access for fraud, material breach, security risk or harmful use. Where appropriate, we will provide notice and an opportunity to remedy the breach. You may stop using Veyra at any time.</p>
  <h2>Governing law and contact</h2><p>These Terms are governed by the laws of the Northern Territory and Australia. Courts located in the Northern Territory have non-exclusive jurisdiction. Contact <a href="mailto:veyrasoft@gmail.com">veyrasoft@gmail.com</a> with questions.</p>
</LegalPage>; }
